### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: https://testnet-api.delta.exchange/v2/positions?product_id=27

### ISSUE THREAD

**Issue by akumar1503** [delta-exchange/python-rest-client#46]
delta_client.get_position(27)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv_p3/lib/python3.11/site-packages/delta_rest_client/delta_rest_client.py", line 138, in get_position
    response = self.request(
               ^^^^^^^^^^^^^
  File "/venv_p3/lib/python3.11/site-packages/delta_rest_client/delta_rest_client.py", line 68, in request
    res.raise_for_status()
  File "/venv_p3/lib/python3.11/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://testnet-api.delta.exchange/v2/positions?product_id=27

**Comment by akumar1503** [comment]
Discussed with PM, a work around:
Whitelisting IPv6 address worked for me.

**Comment by 18patti** [comment]
Hi
I whitelisted my ipv4 address but still the error is throwing. I checked the api key and secret are valid as well.

line 21, in <module>
    order_response = delta_client.place_order(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 234, in place_order
    return self.create_order(order)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 91, in create_order
    response = self.request('POST', "/v2/orders", order, auth=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 68, in request
    res.raise_for_status()
  File "C:\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.delta.exchange/v2/orders

Thanks

**Comment by Chap92** [comment]
> Hi I whitelisted my ipv4 address but still the error is throwing. I checked the api key and secret are valid as well.
> 
> line 21, in order_response = delta_client.place_order( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 234, in place_order return self.create_order(order) ^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 91, in create_order response = self.request('POST', "/v2/orders", order, auth=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\delta_rest_client\delta_rest_client.py", line 68, in request res.raise_for_status() File "C:\Python312\Lib\site-packages\requests\models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.delta.exchange/v2/orders
> 
> Thanks

You need to add both IPV6 and IPV4 addresses, in that order (IPV6 address,IPV4 address)
